Sign-up
wolox-training/ec-express-ts pull request #7
Opened 2022-11-11 21:12 UTC by Emiliocaamano

## Summary

Sign up implementations

## Known Issues

None

## Trello Card

https://trello.com/c/YliS0T84

2022-11-15 14:04 UTC, javerBenavidez requested changes

2022-11-15 14:04 UTC, javerBenavidez commented on app/controllers/users.ts
> +  const cryptPassword = bcrypt.hashSync(req.body.password, Number(10));
Es mejor delegar esta tarea a un archivo en la carpeta helper, recuerda que estos métodos o funciones pueden ser utilizadas por otros métodos y tenerlo como helper ayudará a que sea una función global y reutilizable.

2022-11-24 22:03 UTC, javerBenavidez reviewed
Hacer falta el helper, no lo veo en los archivos nuevos

2022-11-25 14:58 UTC, javerBenavidez approved these changes

2022-11-25 15:17 UTC, merged

2022-11-25 18:30 UTC, elcorren commented on app/controllers/users.ts
> +  const cryptPassword = await parser.passwordParser(req.body.password);
Solo como observación, quizás sea más claro llamar "hashPassword" al helper 💡